// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Polar.OpenAPI.Models
{
    /// <summary>The type of the benefit.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BenefitType
    {
        [EnumMember(Value = "custom")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
        [EnumMember(Value = "discord")]
        #pragma warning disable CS1591
        Discord,
        #pragma warning restore CS1591
        [EnumMember(Value = "github_repository")]
        #pragma warning disable CS1591
        Github_repository,
        #pragma warning restore CS1591
        [EnumMember(Value = "downloadables")]
        #pragma warning disable CS1591
        Downloadables,
        #pragma warning restore CS1591
        [EnumMember(Value = "license_keys")]
        #pragma warning disable CS1591
        License_keys,
        #pragma warning restore CS1591
        [EnumMember(Value = "meter_credit")]
        #pragma warning disable CS1591
        Meter_credit,
        #pragma warning restore CS1591
    }
}
