// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Polar.OpenAPI.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BenefitLicenseKeysSubscriber : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Creation timestamp of the object.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Whether the benefit is deletable.</summary>
        public bool? Deletable { get; set; }
        /// <summary>The description of the benefit.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The ID of the benefit.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Last modification timestamp of the object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber.BenefitLicenseKeysSubscriber_modified_at? ModifiedAt { get; set; }
#nullable restore
#else
        public global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber.BenefitLicenseKeysSubscriber_modified_at ModifiedAt { get; set; }
#endif
        /// <summary>The organization property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Polar.OpenAPI.Models.Organization? Organization { get; set; }
#nullable restore
#else
        public global::Polar.OpenAPI.Models.Organization Organization { get; set; }
#endif
        /// <summary>The ID of the organization owning the benefit.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The properties property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriberProperties? Properties { get; set; }
#nullable restore
#else
        public global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriberProperties Properties { get; set; }
#endif
        /// <summary>Whether the benefit is selectable when creating a product.</summary>
        public bool? Selectable { get; set; }
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber"/> and sets the default values.
        /// </summary>
        public BenefitLicenseKeysSubscriber()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "deletable", n => { Deletable = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "modified_at", n => { ModifiedAt = n.GetObjectValue<global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber.BenefitLicenseKeysSubscriber_modified_at>(global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber.BenefitLicenseKeysSubscriber_modified_at.CreateFromDiscriminatorValue); } },
                { "organization", n => { Organization = n.GetObjectValue<global::Polar.OpenAPI.Models.Organization>(global::Polar.OpenAPI.Models.Organization.CreateFromDiscriminatorValue); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "properties", n => { Properties = n.GetObjectValue<global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriberProperties>(global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriberProperties.CreateFromDiscriminatorValue); } },
                { "selectable", n => { Selectable = n.GetBoolValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteBoolValue("deletable", Deletable);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber.BenefitLicenseKeysSubscriber_modified_at>("modified_at", ModifiedAt);
            writer.WriteObjectValue<global::Polar.OpenAPI.Models.Organization>("organization", Organization);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteObjectValue<global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriberProperties>("properties", Properties);
            writer.WriteBoolValue("selectable", Selectable);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber_modified_atMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BenefitLicenseKeysSubscriber_modified_at : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber_modified_atMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber_modified_atMember1? BenefitLicenseKeysSubscriberModifiedAtMember1 { get; set; }
#nullable restore
#else
            public global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber_modified_atMember1 BenefitLicenseKeysSubscriberModifiedAtMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber.BenefitLicenseKeysSubscriber_modified_at"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber.BenefitLicenseKeysSubscriber_modified_at CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber.BenefitLicenseKeysSubscriber_modified_at();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.BenefitLicenseKeysSubscriberModifiedAtMember1 = new global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber_modified_atMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(BenefitLicenseKeysSubscriberModifiedAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(BenefitLicenseKeysSubscriberModifiedAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::Polar.OpenAPI.Models.BenefitLicenseKeysSubscriber_modified_atMember1>(null, BenefitLicenseKeysSubscriberModifiedAtMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
