// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Polar.OpenAPI.Models
{
    /// <summary>Status of the checkout session.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CheckoutStatus
    {
        [EnumMember(Value = "open")]
        #pragma warning disable CS1591
        Open,
        #pragma warning restore CS1591
        [EnumMember(Value = "expired")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
        [EnumMember(Value = "confirmed")]
        #pragma warning disable CS1591
        Confirmed,
        #pragma warning restore CS1591
        [EnumMember(Value = "succeeded")]
        #pragma warning disable CS1591
        Succeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
    }
}
