// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Polar.OpenAPI.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DiscountDuration
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "once")]
        #pragma warning disable CS1591
        Once,
        #pragma warning restore CS1591
        [EnumMember(Value = "forever")]
        #pragma warning disable CS1591
        Forever,
        #pragma warning restore CS1591
        [EnumMember(Value = "repeating")]
        #pragma warning disable CS1591
        Repeating,
        #pragma warning restore CS1591
    }
}
