// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Polar.OpenAPI.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DiscountType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "fixed")]
        #pragma warning disable CS1591
        Fixed,
        #pragma warning restore CS1591
        [EnumMember(Value = "percentage")]
        #pragma warning disable CS1591
        Percentage,
        #pragma warning restore CS1591
    }
}
