// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Polar.OpenAPI.Models
{
    /// <summary>
    /// Schema to create a pay-what-you-want price.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductPriceCustomCreate : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AmountType { get; set; }
#nullable restore
#else
        public string AmountType { get; set; }
#endif
        /// <summary>The maximum amount the customer can pay.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_maximum_amount? MaximumAmount { get; set; }
#nullable restore
#else
        public global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_maximum_amount MaximumAmount { get; set; }
#endif
        /// <summary>The minimum amount the customer can pay.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_minimum_amount? MinimumAmount { get; set; }
#nullable restore
#else
        public global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_minimum_amount MinimumAmount { get; set; }
#endif
        /// <summary>The initial amount shown to the customer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_preset_amount? PresetAmount { get; set; }
#nullable restore
#else
        public global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_preset_amount PresetAmount { get; set; }
#endif
        /// <summary>The currency. Currently, only `usd` is supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PriceCurrency { get; set; }
#nullable restore
#else
        public string PriceCurrency { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Polar.OpenAPI.Models.ProductPriceCustomCreate"/> and sets the default values.
        /// </summary>
        public ProductPriceCustomCreate()
        {
            AdditionalData = new Dictionary<string, object>();
            PriceCurrency = "usd";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Polar.OpenAPI.Models.ProductPriceCustomCreate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Polar.OpenAPI.Models.ProductPriceCustomCreate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Polar.OpenAPI.Models.ProductPriceCustomCreate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount_type", n => { AmountType = n.GetStringValue(); } },
                { "maximum_amount", n => { MaximumAmount = n.GetObjectValue<global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_maximum_amount>(global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_maximum_amount.CreateFromDiscriminatorValue); } },
                { "minimum_amount", n => { MinimumAmount = n.GetObjectValue<global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_minimum_amount>(global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_minimum_amount.CreateFromDiscriminatorValue); } },
                { "preset_amount", n => { PresetAmount = n.GetObjectValue<global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_preset_amount>(global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_preset_amount.CreateFromDiscriminatorValue); } },
                { "price_currency", n => { PriceCurrency = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("amount_type", AmountType);
            writer.WriteObjectValue<global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_maximum_amount>("maximum_amount", MaximumAmount);
            writer.WriteObjectValue<global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_minimum_amount>("minimum_amount", MinimumAmount);
            writer.WriteObjectValue<global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_preset_amount>("preset_amount", PresetAmount);
            writer.WriteStringValue("price_currency", PriceCurrency);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Polar.OpenAPI.Models.ProductPriceCustomCreate_maximum_amountMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductPriceCustomCreate_maximum_amount : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Polar.OpenAPI.Models.ProductPriceCustomCreate_maximum_amountMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Polar.OpenAPI.Models.ProductPriceCustomCreate_maximum_amountMember1? ProductPriceCustomCreateMaximumAmountMember1 { get; set; }
#nullable restore
#else
            public global::Polar.OpenAPI.Models.ProductPriceCustomCreate_maximum_amountMember1 ProductPriceCustomCreateMaximumAmountMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_maximum_amount"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_maximum_amount CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_maximum_amount();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.ProductPriceCustomCreateMaximumAmountMember1 = new global::Polar.OpenAPI.Models.ProductPriceCustomCreate_maximum_amountMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ProductPriceCustomCreateMaximumAmountMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ProductPriceCustomCreateMaximumAmountMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Polar.OpenAPI.Models.ProductPriceCustomCreate_maximum_amountMember1>(null, ProductPriceCustomCreateMaximumAmountMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Polar.OpenAPI.Models.ProductPriceCustomCreate_minimum_amountMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductPriceCustomCreate_minimum_amount : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Polar.OpenAPI.Models.ProductPriceCustomCreate_minimum_amountMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Polar.OpenAPI.Models.ProductPriceCustomCreate_minimum_amountMember1? ProductPriceCustomCreateMinimumAmountMember1 { get; set; }
#nullable restore
#else
            public global::Polar.OpenAPI.Models.ProductPriceCustomCreate_minimum_amountMember1 ProductPriceCustomCreateMinimumAmountMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_minimum_amount"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_minimum_amount CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_minimum_amount();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.ProductPriceCustomCreateMinimumAmountMember1 = new global::Polar.OpenAPI.Models.ProductPriceCustomCreate_minimum_amountMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ProductPriceCustomCreateMinimumAmountMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ProductPriceCustomCreateMinimumAmountMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Polar.OpenAPI.Models.ProductPriceCustomCreate_minimum_amountMember1>(null, ProductPriceCustomCreateMinimumAmountMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Polar.OpenAPI.Models.ProductPriceCustomCreate_preset_amountMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductPriceCustomCreate_preset_amount : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Polar.OpenAPI.Models.ProductPriceCustomCreate_preset_amountMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Polar.OpenAPI.Models.ProductPriceCustomCreate_preset_amountMember1? ProductPriceCustomCreatePresetAmountMember1 { get; set; }
#nullable restore
#else
            public global::Polar.OpenAPI.Models.ProductPriceCustomCreate_preset_amountMember1 ProductPriceCustomCreatePresetAmountMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_preset_amount"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_preset_amount CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Polar.OpenAPI.Models.ProductPriceCustomCreate.ProductPriceCustomCreate_preset_amount();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.ProductPriceCustomCreatePresetAmountMember1 = new global::Polar.OpenAPI.Models.ProductPriceCustomCreate_preset_amountMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ProductPriceCustomCreatePresetAmountMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ProductPriceCustomCreatePresetAmountMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Polar.OpenAPI.Models.ProductPriceCustomCreate_preset_amountMember1>(null, ProductPriceCustomCreatePresetAmountMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
