// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Polar.OpenAPI.V1.CustomerPortal.Organizations.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Polar.OpenAPI.V1.CustomerPortal.Organizations
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\customer-portal\organizations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrganizationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Polar.OpenAPI.v1.customerPortal.organizations.item collection</summary>
        /// <param name="position">The organization slug.</param>
        /// <returns>A <see cref="global::Polar.OpenAPI.V1.CustomerPortal.Organizations.Item.WithSlugItemRequestBuilder"/></returns>
        public global::Polar.OpenAPI.V1.CustomerPortal.Organizations.Item.WithSlugItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("slug", position);
                return new global::Polar.OpenAPI.V1.CustomerPortal.Organizations.Item.WithSlugItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Polar.OpenAPI.V1.CustomerPortal.Organizations.OrganizationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrganizationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/customer-portal/organizations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Polar.OpenAPI.V1.CustomerPortal.Organizations.OrganizationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrganizationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/customer-portal/organizations", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
