// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomFieldTextProperties : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The form_help_text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FormHelpText { get; set; }
#nullable restore
#else
        public string FormHelpText { get; set; }
#endif
        /// <summary>The form_label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FormLabel { get; set; }
#nullable restore
#else
        public string FormLabel { get; set; }
#endif
        /// <summary>The form_placeholder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FormPlaceholder { get; set; }
#nullable restore
#else
        public string FormPlaceholder { get; set; }
#endif
        /// <summary>The max_length property</summary>
        public int? MaxLength { get; set; }
        /// <summary>The min_length property</summary>
        public int? MinLength { get; set; }
        /// <summary>The textarea property</summary>
        public bool? Textarea { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.CustomFieldTextProperties"/> and sets the default values.
        /// </summary>
        public CustomFieldTextProperties()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.CustomFieldTextProperties"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.CustomFieldTextProperties CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.CustomFieldTextProperties();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "form_help_text", n => { FormHelpText = n.GetStringValue(); } },
                { "form_label", n => { FormLabel = n.GetStringValue(); } },
                { "form_placeholder", n => { FormPlaceholder = n.GetStringValue(); } },
                { "max_length", n => { MaxLength = n.GetIntValue(); } },
                { "min_length", n => { MinLength = n.GetIntValue(); } },
                { "textarea", n => { Textarea = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("form_help_text", FormHelpText);
            writer.WriteStringValue("form_label", FormLabel);
            writer.WriteStringValue("form_placeholder", FormPlaceholder);
            writer.WriteIntValue("max_length", MaxLength);
            writer.WriteIntValue("min_length", MinLength);
            writer.WriteBoolValue("textarea", Textarea);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
