// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// Schema for a percentage discount that is applied on every invoicefor a certain number of months.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DiscountPercentageRepeatDuration : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The basis_points property</summary>
        public int? BasisPoints { get; set; }
        /// <summary>Code customers can use to apply the discount during checkout.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_code? Code { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_code Code { get; set; }
#endif
        /// <summary>Creation timestamp of the object.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The duration property</summary>
        public global::ApiSdk.Models.DiscountDuration? Duration { get; set; }
        /// <summary>The duration_in_months property</summary>
        public int? DurationInMonths { get; set; }
        /// <summary>Timestamp after which the discount is no longer redeemable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_ends_at? EndsAt { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_ends_at EndsAt { get; set; }
#endif
        /// <summary>The ID of the object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Maximum number of times the discount can be redeemed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_max_redemptions? MaxRedemptions { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_max_redemptions MaxRedemptions { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.DiscountPercentageRepeatDuration_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.DiscountPercentageRepeatDuration_metadata Metadata { get; set; }
#endif
        /// <summary>Last modification timestamp of the object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_modified_at? ModifiedAt { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_modified_at ModifiedAt { get; set; }
#endif
        /// <summary>Name of the discount. Will be displayed to the customer when the discount is applied.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The organization ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The products property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.DiscountProduct>? Products { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.DiscountProduct> Products { get; set; }
#endif
        /// <summary>Number of times the discount has been redeemed.</summary>
        public int? RedemptionsCount { get; set; }
        /// <summary>Timestamp after which the discount is redeemable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_starts_at? StartsAt { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_starts_at StartsAt { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::ApiSdk.Models.DiscountType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration"/> and sets the default values.
        /// </summary>
        public DiscountPercentageRepeatDuration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.DiscountPercentageRepeatDuration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.DiscountPercentageRepeatDuration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "basis_points", n => { BasisPoints = n.GetIntValue(); } },
                { "code", n => { Code = n.GetObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_code>(global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_code.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "duration", n => { Duration = n.GetEnumValue<global::ApiSdk.Models.DiscountDuration>(); } },
                { "duration_in_months", n => { DurationInMonths = n.GetIntValue(); } },
                { "ends_at", n => { EndsAt = n.GetObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_ends_at>(global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_ends_at.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "max_redemptions", n => { MaxRedemptions = n.GetObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_max_redemptions>(global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_max_redemptions.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration_metadata>(global::ApiSdk.Models.DiscountPercentageRepeatDuration_metadata.CreateFromDiscriminatorValue); } },
                { "modified_at", n => { ModifiedAt = n.GetObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_modified_at>(global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_modified_at.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "products", n => { Products = n.GetCollectionOfObjectValues<global::ApiSdk.Models.DiscountProduct>(global::ApiSdk.Models.DiscountProduct.CreateFromDiscriminatorValue)?.AsList(); } },
                { "redemptions_count", n => { RedemptionsCount = n.GetIntValue(); } },
                { "starts_at", n => { StartsAt = n.GetObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_starts_at>(global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_starts_at.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::ApiSdk.Models.DiscountType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("basis_points", BasisPoints);
            writer.WriteObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_code>("code", Code);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteEnumValue<global::ApiSdk.Models.DiscountDuration>("duration", Duration);
            writer.WriteIntValue("duration_in_months", DurationInMonths);
            writer.WriteObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_ends_at>("ends_at", EndsAt);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_max_redemptions>("max_redemptions", MaxRedemptions);
            writer.WriteObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration_metadata>("metadata", Metadata);
            writer.WriteObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_modified_at>("modified_at", ModifiedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.DiscountProduct>("products", Products);
            writer.WriteIntValue("redemptions_count", RedemptionsCount);
            writer.WriteObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_starts_at>("starts_at", StartsAt);
            writer.WriteEnumValue<global::ApiSdk.Models.DiscountType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration_codeMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DiscountPercentageRepeatDuration_code : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration_codeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.DiscountPercentageRepeatDuration_codeMember1? DiscountPercentageRepeatDurationCodeMember1 { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.DiscountPercentageRepeatDuration_codeMember1 DiscountPercentageRepeatDurationCodeMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_code"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_code CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_code();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.DiscountPercentageRepeatDurationCodeMember1 = new global::ApiSdk.Models.DiscountPercentageRepeatDuration_codeMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(DiscountPercentageRepeatDurationCodeMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(DiscountPercentageRepeatDurationCodeMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration_codeMember1>(null, DiscountPercentageRepeatDurationCodeMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration_ends_atMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DiscountPercentageRepeatDuration_ends_at : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration_ends_atMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.DiscountPercentageRepeatDuration_ends_atMember1? DiscountPercentageRepeatDurationEndsAtMember1 { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.DiscountPercentageRepeatDuration_ends_atMember1 DiscountPercentageRepeatDurationEndsAtMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_ends_at"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_ends_at CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_ends_at();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.DiscountPercentageRepeatDurationEndsAtMember1 = new global::ApiSdk.Models.DiscountPercentageRepeatDuration_ends_atMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(DiscountPercentageRepeatDurationEndsAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(DiscountPercentageRepeatDurationEndsAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration_ends_atMember1>(null, DiscountPercentageRepeatDurationEndsAtMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration_max_redemptionsMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DiscountPercentageRepeatDuration_max_redemptions : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration_max_redemptionsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.DiscountPercentageRepeatDuration_max_redemptionsMember1? DiscountPercentageRepeatDurationMaxRedemptionsMember1 { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.DiscountPercentageRepeatDuration_max_redemptionsMember1 DiscountPercentageRepeatDurationMaxRedemptionsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_max_redemptions"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_max_redemptions CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_max_redemptions();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.DiscountPercentageRepeatDurationMaxRedemptionsMember1 = new global::ApiSdk.Models.DiscountPercentageRepeatDuration_max_redemptionsMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(DiscountPercentageRepeatDurationMaxRedemptionsMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(DiscountPercentageRepeatDurationMaxRedemptionsMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration_max_redemptionsMember1>(null, DiscountPercentageRepeatDurationMaxRedemptionsMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration_modified_atMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DiscountPercentageRepeatDuration_modified_at : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration_modified_atMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.DiscountPercentageRepeatDuration_modified_atMember1? DiscountPercentageRepeatDurationModifiedAtMember1 { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.DiscountPercentageRepeatDuration_modified_atMember1 DiscountPercentageRepeatDurationModifiedAtMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_modified_at"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_modified_at CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_modified_at();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.DiscountPercentageRepeatDurationModifiedAtMember1 = new global::ApiSdk.Models.DiscountPercentageRepeatDuration_modified_atMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(DiscountPercentageRepeatDurationModifiedAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(DiscountPercentageRepeatDurationModifiedAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration_modified_atMember1>(null, DiscountPercentageRepeatDurationModifiedAtMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration_starts_atMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DiscountPercentageRepeatDuration_starts_at : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration_starts_atMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.DiscountPercentageRepeatDuration_starts_atMember1? DiscountPercentageRepeatDurationStartsAtMember1 { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.DiscountPercentageRepeatDuration_starts_atMember1 DiscountPercentageRepeatDurationStartsAtMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_starts_at"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_starts_at CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::ApiSdk.Models.DiscountPercentageRepeatDuration.DiscountPercentageRepeatDuration_starts_at();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.DiscountPercentageRepeatDurationStartsAtMember1 = new global::ApiSdk.Models.DiscountPercentageRepeatDuration_starts_atMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(DiscountPercentageRepeatDurationStartsAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(DiscountPercentageRepeatDurationStartsAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::ApiSdk.Models.DiscountPercentageRepeatDuration_starts_atMember1>(null, DiscountPercentageRepeatDurationStartsAtMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
