// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EventCreateExternalCustomer : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ID of the customer in your system associated with the event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalCustomerId { get; set; }
#nullable restore
#else
        public string ExternalCustomerId { get; set; }
#endif
        /// <summary>Key-value object allowing you to store additional information.The key must be a string with a maximum length of **40 characters**.The value must be either:* A string with a maximum length of **500 characters*** An integer* A booleanYou can store up to **50 key-value pairs**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.EventCreateExternalCustomer_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.EventCreateExternalCustomer_metadata Metadata { get; set; }
#endif
        /// <summary>The name of the event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ID of the organization owning the event. **Required unless you use an organization token.**</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.EventCreateExternalCustomer.EventCreateExternalCustomer_organization_id? OrganizationId { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.EventCreateExternalCustomer.EventCreateExternalCustomer_organization_id OrganizationId { get; set; }
#endif
        /// <summary>The timestamp of the event.</summary>
        public DateTimeOffset? Timestamp { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.EventCreateExternalCustomer"/> and sets the default values.
        /// </summary>
        public EventCreateExternalCustomer()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.EventCreateExternalCustomer"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.EventCreateExternalCustomer CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.EventCreateExternalCustomer();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "external_customer_id", n => { ExternalCustomerId = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::ApiSdk.Models.EventCreateExternalCustomer_metadata>(global::ApiSdk.Models.EventCreateExternalCustomer_metadata.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetObjectValue<global::ApiSdk.Models.EventCreateExternalCustomer.EventCreateExternalCustomer_organization_id>(global::ApiSdk.Models.EventCreateExternalCustomer.EventCreateExternalCustomer_organization_id.CreateFromDiscriminatorValue); } },
                { "timestamp", n => { Timestamp = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("external_customer_id", ExternalCustomerId);
            writer.WriteObjectValue<global::ApiSdk.Models.EventCreateExternalCustomer_metadata>("metadata", Metadata);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::ApiSdk.Models.EventCreateExternalCustomer.EventCreateExternalCustomer_organization_id>("organization_id", OrganizationId);
            writer.WriteDateTimeOffsetValue("timestamp", Timestamp);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::ApiSdk.Models.EventCreateExternalCustomer_organization_idMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EventCreateExternalCustomer_organization_id : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.EventCreateExternalCustomer_organization_idMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.EventCreateExternalCustomer_organization_idMember1? EventCreateExternalCustomerOrganizationIdMember1 { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.EventCreateExternalCustomer_organization_idMember1 EventCreateExternalCustomerOrganizationIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.EventCreateExternalCustomer.EventCreateExternalCustomer_organization_id"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.EventCreateExternalCustomer.EventCreateExternalCustomer_organization_id CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::ApiSdk.Models.EventCreateExternalCustomer.EventCreateExternalCustomer_organization_id();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.EventCreateExternalCustomerOrganizationIdMember1 = new global::ApiSdk.Models.EventCreateExternalCustomer_organization_idMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(EventCreateExternalCustomerOrganizationIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(EventCreateExternalCustomerOrganizationIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::ApiSdk.Models.EventCreateExternalCustomer_organization_idMember1>(null, EventCreateExternalCustomerOrganizationIdMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
