// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Order : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Amount in cents, after discounts but before taxes.</summary>
        [Obsolete("")]
        public int? Amount { get; set; }
        /// <summary>The billing_address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.Address? BillingAddress { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.Address BillingAddress { get; set; }
#endif
        /// <summary>The billing_reason property</summary>
        public global::ApiSdk.Models.OrderBillingReason? BillingReason { get; set; }
        /// <summary>The checkout_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.Order.Order_checkout_id? CheckoutId { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.Order.Order_checkout_id CheckoutId { get; set; }
#endif
        /// <summary>Creation timestamp of the object.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>The customer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.OrderCustomer? Customer { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.OrderCustomer Customer { get; set; }
#endif
        /// <summary>The customer_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerId { get; set; }
#nullable restore
#else
        public string CustomerId { get; set; }
#endif
        /// <summary>Key-value object storing custom field values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.Order_custom_field_data? CustomFieldData { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.Order_custom_field_data CustomFieldData { get; set; }
#endif
        /// <summary>The discount property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Discount { get; set; }
#nullable restore
#else
        public UntypedNode Discount { get; set; }
#endif
        /// <summary>Discount amount in cents.</summary>
        public int? DiscountAmount { get; set; }
        /// <summary>The discount_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.Order.Order_discount_id? DiscountId { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.Order.Order_discount_id DiscountId { get; set; }
#endif
        /// <summary>The ID of the object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Line items composing the order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.OrderItemSchema>? Items { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.OrderItemSchema> Items { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.Order_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.Order_metadata Metadata { get; set; }
#endif
        /// <summary>Last modification timestamp of the object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.Order.Order_modified_at? ModifiedAt { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.Order.Order_modified_at ModifiedAt { get; set; }
#endif
        /// <summary>Amount in cents, after discounts but before taxes.</summary>
        public int? NetAmount { get; set; }
        /// <summary>Whether the order has been paid for.</summary>
        public bool? Paid { get; set; }
        /// <summary>The product property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.OrderProduct? Product { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.OrderProduct Product { get; set; }
#endif
        /// <summary>The product_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductId { get; set; }
#nullable restore
#else
        public string ProductId { get; set; }
#endif
        /// <summary>The product_price property</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.Order.Order_product_price? ProductPrice { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.Order.Order_product_price ProductPrice { get; set; }
#endif
        /// <summary>The product_price_id property</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductPriceId { get; set; }
#nullable restore
#else
        public string ProductPriceId { get; set; }
#endif
        /// <summary>Amount refunded in cents.</summary>
        public int? RefundedAmount { get; set; }
        /// <summary>Sales tax refunded in cents.</summary>
        public int? RefundedTaxAmount { get; set; }
        /// <summary>The status property</summary>
        public global::ApiSdk.Models.OrderStatus? Status { get; set; }
        /// <summary>The subscription property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.OrderSubscription? Subscription { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.OrderSubscription Subscription { get; set; }
#endif
        /// <summary>The subscription_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.Order.Order_subscription_id? SubscriptionId { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.Order.Order_subscription_id SubscriptionId { get; set; }
#endif
        /// <summary>Amount in cents, before discounts and taxes.</summary>
        public int? SubtotalAmount { get; set; }
        /// <summary>Sales tax amount in cents.</summary>
        public int? TaxAmount { get; set; }
        /// <summary>Amount in cents, after discounts and taxes.</summary>
        public int? TotalAmount { get; set; }
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.OrderUser? User { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.OrderUser User { get; set; }
#endif
        /// <summary>The user_id property</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.Order"/> and sets the default values.
        /// </summary>
        public Order()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.Order"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.Order CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.Order();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetIntValue(); } },
                { "billing_address", n => { BillingAddress = n.GetObjectValue<global::ApiSdk.Models.Address>(global::ApiSdk.Models.Address.CreateFromDiscriminatorValue); } },
                { "billing_reason", n => { BillingReason = n.GetEnumValue<global::ApiSdk.Models.OrderBillingReason>(); } },
                { "checkout_id", n => { CheckoutId = n.GetObjectValue<global::ApiSdk.Models.Order.Order_checkout_id>(global::ApiSdk.Models.Order.Order_checkout_id.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "custom_field_data", n => { CustomFieldData = n.GetObjectValue<global::ApiSdk.Models.Order_custom_field_data>(global::ApiSdk.Models.Order_custom_field_data.CreateFromDiscriminatorValue); } },
                { "customer", n => { Customer = n.GetObjectValue<global::ApiSdk.Models.OrderCustomer>(global::ApiSdk.Models.OrderCustomer.CreateFromDiscriminatorValue); } },
                { "customer_id", n => { CustomerId = n.GetStringValue(); } },
                { "discount", n => { Discount = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "discount_amount", n => { DiscountAmount = n.GetIntValue(); } },
                { "discount_id", n => { DiscountId = n.GetObjectValue<global::ApiSdk.Models.Order.Order_discount_id>(global::ApiSdk.Models.Order.Order_discount_id.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::ApiSdk.Models.OrderItemSchema>(global::ApiSdk.Models.OrderItemSchema.CreateFromDiscriminatorValue)?.AsList(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::ApiSdk.Models.Order_metadata>(global::ApiSdk.Models.Order_metadata.CreateFromDiscriminatorValue); } },
                { "modified_at", n => { ModifiedAt = n.GetObjectValue<global::ApiSdk.Models.Order.Order_modified_at>(global::ApiSdk.Models.Order.Order_modified_at.CreateFromDiscriminatorValue); } },
                { "net_amount", n => { NetAmount = n.GetIntValue(); } },
                { "paid", n => { Paid = n.GetBoolValue(); } },
                { "product", n => { Product = n.GetObjectValue<global::ApiSdk.Models.OrderProduct>(global::ApiSdk.Models.OrderProduct.CreateFromDiscriminatorValue); } },
                { "product_id", n => { ProductId = n.GetStringValue(); } },
                { "product_price", n => { ProductPrice = n.GetObjectValue<global::ApiSdk.Models.Order.Order_product_price>(global::ApiSdk.Models.Order.Order_product_price.CreateFromDiscriminatorValue); } },
                { "product_price_id", n => { ProductPriceId = n.GetStringValue(); } },
                { "refunded_amount", n => { RefundedAmount = n.GetIntValue(); } },
                { "refunded_tax_amount", n => { RefundedTaxAmount = n.GetIntValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::ApiSdk.Models.OrderStatus>(); } },
                { "subscription", n => { Subscription = n.GetObjectValue<global::ApiSdk.Models.OrderSubscription>(global::ApiSdk.Models.OrderSubscription.CreateFromDiscriminatorValue); } },
                { "subscription_id", n => { SubscriptionId = n.GetObjectValue<global::ApiSdk.Models.Order.Order_subscription_id>(global::ApiSdk.Models.Order.Order_subscription_id.CreateFromDiscriminatorValue); } },
                { "subtotal_amount", n => { SubtotalAmount = n.GetIntValue(); } },
                { "tax_amount", n => { TaxAmount = n.GetIntValue(); } },
                { "total_amount", n => { TotalAmount = n.GetIntValue(); } },
                { "user", n => { User = n.GetObjectValue<global::ApiSdk.Models.OrderUser>(global::ApiSdk.Models.OrderUser.CreateFromDiscriminatorValue); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("amount", Amount);
            writer.WriteObjectValue<global::ApiSdk.Models.Address>("billing_address", BillingAddress);
            writer.WriteEnumValue<global::ApiSdk.Models.OrderBillingReason>("billing_reason", BillingReason);
            writer.WriteObjectValue<global::ApiSdk.Models.Order.Order_checkout_id>("checkout_id", CheckoutId);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("currency", Currency);
            writer.WriteObjectValue<global::ApiSdk.Models.OrderCustomer>("customer", Customer);
            writer.WriteStringValue("customer_id", CustomerId);
            writer.WriteObjectValue<global::ApiSdk.Models.Order_custom_field_data>("custom_field_data", CustomFieldData);
            writer.WriteObjectValue<UntypedNode>("discount", Discount);
            writer.WriteIntValue("discount_amount", DiscountAmount);
            writer.WriteObjectValue<global::ApiSdk.Models.Order.Order_discount_id>("discount_id", DiscountId);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.OrderItemSchema>("items", Items);
            writer.WriteObjectValue<global::ApiSdk.Models.Order_metadata>("metadata", Metadata);
            writer.WriteObjectValue<global::ApiSdk.Models.Order.Order_modified_at>("modified_at", ModifiedAt);
            writer.WriteIntValue("net_amount", NetAmount);
            writer.WriteBoolValue("paid", Paid);
            writer.WriteObjectValue<global::ApiSdk.Models.OrderProduct>("product", Product);
            writer.WriteStringValue("product_id", ProductId);
            writer.WriteObjectValue<global::ApiSdk.Models.Order.Order_product_price>("product_price", ProductPrice);
            writer.WriteStringValue("product_price_id", ProductPriceId);
            writer.WriteIntValue("refunded_amount", RefundedAmount);
            writer.WriteIntValue("refunded_tax_amount", RefundedTaxAmount);
            writer.WriteEnumValue<global::ApiSdk.Models.OrderStatus>("status", Status);
            writer.WriteObjectValue<global::ApiSdk.Models.OrderSubscription>("subscription", Subscription);
            writer.WriteObjectValue<global::ApiSdk.Models.Order.Order_subscription_id>("subscription_id", SubscriptionId);
            writer.WriteIntValue("subtotal_amount", SubtotalAmount);
            writer.WriteIntValue("tax_amount", TaxAmount);
            writer.WriteIntValue("total_amount", TotalAmount);
            writer.WriteObjectValue<global::ApiSdk.Models.OrderUser>("user", User);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::ApiSdk.Models.Order_checkout_idMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Order_checkout_id : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.Order_checkout_idMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.Order_checkout_idMember1? OrderCheckoutIdMember1 { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.Order_checkout_idMember1 OrderCheckoutIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.Order.Order_checkout_id"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.Order.Order_checkout_id CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::ApiSdk.Models.Order.Order_checkout_id();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.OrderCheckoutIdMember1 = new global::ApiSdk.Models.Order_checkout_idMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OrderCheckoutIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(OrderCheckoutIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::ApiSdk.Models.Order_checkout_idMember1>(null, OrderCheckoutIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::ApiSdk.Models.Order_discount_idMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Order_discount_id : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.Order_discount_idMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.Order_discount_idMember1? OrderDiscountIdMember1 { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.Order_discount_idMember1 OrderDiscountIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.Order.Order_discount_id"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.Order.Order_discount_id CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::ApiSdk.Models.Order.Order_discount_id();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.OrderDiscountIdMember1 = new global::ApiSdk.Models.Order_discount_idMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OrderDiscountIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(OrderDiscountIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::ApiSdk.Models.Order_discount_idMember1>(null, OrderDiscountIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::ApiSdk.Models.Order_modified_atMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Order_modified_at : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.Order_modified_atMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.Order_modified_atMember1? OrderModifiedAtMember1 { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.Order_modified_atMember1 OrderModifiedAtMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.Order.Order_modified_at"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.Order.Order_modified_at CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::ApiSdk.Models.Order.Order_modified_at();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.OrderModifiedAtMember1 = new global::ApiSdk.Models.Order_modified_atMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OrderModifiedAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(OrderModifiedAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::ApiSdk.Models.Order_modified_atMember1>(null, OrderModifiedAtMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::ApiSdk.Models.LegacyRecurringProductPrice"/>, <see cref="global::ApiSdk.Models.ProductPrice"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Order_product_price : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.LegacyRecurringProductPrice"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.LegacyRecurringProductPrice? LegacyRecurringProductPrice { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.LegacyRecurringProductPrice LegacyRecurringProductPrice { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.ProductPrice"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.ProductPrice? ProductPrice { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.ProductPrice ProductPrice { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.Order.Order_product_price"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.Order.Order_product_price CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("amount_type")?.GetStringValue();
                var result = new global::ApiSdk.Models.Order.Order_product_price();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.LegacyRecurringProductPrice = new global::ApiSdk.Models.LegacyRecurringProductPrice();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProductPrice = new global::ApiSdk.Models.ProductPrice();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(LegacyRecurringProductPrice != null)
                {
                    return LegacyRecurringProductPrice.GetFieldDeserializers();
                }
                else if(ProductPrice != null)
                {
                    return ProductPrice.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(LegacyRecurringProductPrice != null)
                {
                    writer.WriteObjectValue<global::ApiSdk.Models.LegacyRecurringProductPrice>(null, LegacyRecurringProductPrice);
                }
                else if(ProductPrice != null)
                {
                    writer.WriteObjectValue<global::ApiSdk.Models.ProductPrice>(null, ProductPrice);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::ApiSdk.Models.Order_subscription_idMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Order_subscription_id : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.Order_subscription_idMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.Order_subscription_idMember1? OrderSubscriptionIdMember1 { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.Order_subscription_idMember1 OrderSubscriptionIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.Order.Order_subscription_id"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.Order.Order_subscription_id CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::ApiSdk.Models.Order.Order_subscription_id();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.OrderSubscriptionIdMember1 = new global::ApiSdk.Models.Order_subscription_idMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OrderSubscriptionIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(OrderSubscriptionIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::ApiSdk.Models.Order_subscription_idMember1>(null, OrderSubscriptionIdMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
