// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// Schema to create a file to be used as an organization avatar.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrganizationAvatarFileCreate : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The checksum_sha256_base64 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_checksum_sha256_base64? ChecksumSha256Base64 { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_checksum_sha256_base64 ChecksumSha256Base64 { get; set; }
#endif
        /// <summary>MIME type of the file. Only images are supported for this type of file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MimeType { get; set; }
#nullable restore
#else
        public string MimeType { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The organization_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_organization_id? OrganizationId { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_organization_id OrganizationId { get; set; }
#endif
        /// <summary>The service property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Service { get; set; }
#nullable restore
#else
        public string Service { get; set; }
#endif
        /// <summary>Size of the file. A maximum of 1 MB is allowed for this type of file.</summary>
        public int? Size { get; set; }
        /// <summary>The upload property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.S3FileCreateMultipart? Upload { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.S3FileCreateMultipart Upload { get; set; }
#endif
        /// <summary>The version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_version? Version { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_version Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.OrganizationAvatarFileCreate"/> and sets the default values.
        /// </summary>
        public OrganizationAvatarFileCreate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.OrganizationAvatarFileCreate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.OrganizationAvatarFileCreate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.OrganizationAvatarFileCreate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checksum_sha256_base64", n => { ChecksumSha256Base64 = n.GetObjectValue<global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_checksum_sha256_base64>(global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_checksum_sha256_base64.CreateFromDiscriminatorValue); } },
                { "mime_type", n => { MimeType = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetObjectValue<global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_organization_id>(global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_organization_id.CreateFromDiscriminatorValue); } },
                { "service", n => { Service = n.GetStringValue(); } },
                { "size", n => { Size = n.GetIntValue(); } },
                { "upload", n => { Upload = n.GetObjectValue<global::ApiSdk.Models.S3FileCreateMultipart>(global::ApiSdk.Models.S3FileCreateMultipart.CreateFromDiscriminatorValue); } },
                { "version", n => { Version = n.GetObjectValue<global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_version>(global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_version.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_checksum_sha256_base64>("checksum_sha256_base64", ChecksumSha256Base64);
            writer.WriteStringValue("mime_type", MimeType);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_organization_id>("organization_id", OrganizationId);
            writer.WriteStringValue("service", Service);
            writer.WriteIntValue("size", Size);
            writer.WriteObjectValue<global::ApiSdk.Models.S3FileCreateMultipart>("upload", Upload);
            writer.WriteObjectValue<global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_version>("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::ApiSdk.Models.OrganizationAvatarFileCreate_checksum_sha256_base64Member1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrganizationAvatarFileCreate_checksum_sha256_base64 : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.OrganizationAvatarFileCreate_checksum_sha256_base64Member1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.OrganizationAvatarFileCreate_checksum_sha256_base64Member1? OrganizationAvatarFileCreateChecksumSha256Base64Member1 { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.OrganizationAvatarFileCreate_checksum_sha256_base64Member1 OrganizationAvatarFileCreateChecksumSha256Base64Member1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_checksum_sha256_base64"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_checksum_sha256_base64 CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_checksum_sha256_base64();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.OrganizationAvatarFileCreateChecksumSha256Base64Member1 = new global::ApiSdk.Models.OrganizationAvatarFileCreate_checksum_sha256_base64Member1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OrganizationAvatarFileCreateChecksumSha256Base64Member1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(OrganizationAvatarFileCreateChecksumSha256Base64Member1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::ApiSdk.Models.OrganizationAvatarFileCreate_checksum_sha256_base64Member1>(null, OrganizationAvatarFileCreateChecksumSha256Base64Member1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::ApiSdk.Models.OrganizationAvatarFileCreate_organization_idMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrganizationAvatarFileCreate_organization_id : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.OrganizationAvatarFileCreate_organization_idMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.OrganizationAvatarFileCreate_organization_idMember1? OrganizationAvatarFileCreateOrganizationIdMember1 { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.OrganizationAvatarFileCreate_organization_idMember1 OrganizationAvatarFileCreateOrganizationIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_organization_id"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_organization_id CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_organization_id();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.OrganizationAvatarFileCreateOrganizationIdMember1 = new global::ApiSdk.Models.OrganizationAvatarFileCreate_organization_idMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OrganizationAvatarFileCreateOrganizationIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(OrganizationAvatarFileCreateOrganizationIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::ApiSdk.Models.OrganizationAvatarFileCreate_organization_idMember1>(null, OrganizationAvatarFileCreateOrganizationIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::ApiSdk.Models.OrganizationAvatarFileCreate_versionMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrganizationAvatarFileCreate_version : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.OrganizationAvatarFileCreate_versionMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.OrganizationAvatarFileCreate_versionMember1? OrganizationAvatarFileCreateVersionMember1 { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.OrganizationAvatarFileCreate_versionMember1 OrganizationAvatarFileCreateVersionMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_version"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_version CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::ApiSdk.Models.OrganizationAvatarFileCreate.OrganizationAvatarFileCreate_version();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.OrganizationAvatarFileCreateVersionMember1 = new global::ApiSdk.Models.OrganizationAvatarFileCreate_versionMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OrganizationAvatarFileCreateVersionMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(OrganizationAvatarFileCreateVersionMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::ApiSdk.Models.OrganizationAvatarFileCreate_versionMember1>(null, OrganizationAvatarFileCreateVersionMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
