// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.V1.Meters.Item.Quantities
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\meters\{id}\quantities
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QuantitiesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Meters.Item.Quantities.QuantitiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QuantitiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/meters/{id}/quantities?end_timestamp={end_timestamp}&interval={interval}&start_timestamp={start_timestamp}{&customer_id*,external_customer_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Meters.Item.Quantities.QuantitiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QuantitiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/meters/{id}/quantities?end_timestamp={end_timestamp}&interval={interval}&start_timestamp={start_timestamp}{&customer_id*,external_customer_id*}", rawUrl)
        {
        }
        /// <summary>
        /// Get quantities of a meter over a time period.**Scopes**: `meters:read` `meters:write`
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.MeterQuantities"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiSdk.Models.ResourceNotFound">When receiving a 404 status code</exception>
        /// <exception cref="global::ApiSdk.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiSdk.Models.MeterQuantities?> GetAsync(Action<RequestConfiguration<global::ApiSdk.V1.Meters.Item.Quantities.QuantitiesRequestBuilder.QuantitiesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiSdk.Models.MeterQuantities> GetAsync(Action<RequestConfiguration<global::ApiSdk.V1.Meters.Item.Quantities.QuantitiesRequestBuilder.QuantitiesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::ApiSdk.Models.ResourceNotFound.CreateFromDiscriminatorValue },
                { "422", global::ApiSdk.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ApiSdk.Models.MeterQuantities>(requestInfo, global::ApiSdk.Models.MeterQuantities.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get quantities of a meter over a time period.**Scopes**: `meters:read` `meters:write`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.V1.Meters.Item.Quantities.QuantitiesRequestBuilder.QuantitiesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.V1.Meters.Item.Quantities.QuantitiesRequestBuilder.QuantitiesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.V1.Meters.Item.Quantities.QuantitiesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiSdk.V1.Meters.Item.Quantities.QuantitiesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ApiSdk.V1.Meters.Item.Quantities.QuantitiesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get quantities of a meter over a time period.**Scopes**: `meters:read` `meters:write`
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class QuantitiesRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter by customer ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("customer_id")]
            public string? CustomerId { get; set; }
#nullable restore
#else
            [QueryParameter("customer_id")]
            public string CustomerId { get; set; }
#endif
            /// <summary>End timestamp.</summary>
            [QueryParameter("end_timestamp")]
            public DateTimeOffset? EndTimestamp { get; set; }
            /// <summary>Filter by external customer ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("external_customer_id")]
            public string? ExternalCustomerId { get; set; }
#nullable restore
#else
            [QueryParameter("external_customer_id")]
            public string ExternalCustomerId { get; set; }
#endif
            /// <summary>Interval between two timestamps.</summary>
            [Obsolete("This property is deprecated, use IntervalAsTimeInterval instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("interval")]
            public string? Interval { get; set; }
#nullable restore
#else
            [QueryParameter("interval")]
            public string Interval { get; set; }
#endif
            /// <summary>Interval between two timestamps.</summary>
            [QueryParameter("interval")]
            public global::ApiSdk.Models.TimeInterval? IntervalAsTimeInterval { get; set; }
            /// <summary>Start timestamp.</summary>
            [QueryParameter("start_timestamp")]
            public DateTimeOffset? StartTimestamp { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class QuantitiesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ApiSdk.V1.Meters.Item.Quantities.QuantitiesRequestBuilder.QuantitiesRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
